using System.Collections.Generic;
using UnityEngine;

public static class DictionaryUtils
{
    public static Dictionary<string, HashSet<string>> bank = new Dictionary<string, HashSet<string>>()
    {
        {
            "YLRAEW", new HashSet<string> { "LAWYER", "EARLY", "LAYER", "LEARY", "RAWLY", "RELAY", "WALER", "WEARY", "AERY", "ARYL", "AWRY", "EARL", "EYRA", "LEAR", "LYRE", "RALE", "REAL", "RELY", "WALE", "WALY", "WARE", "WARY", "WEAL", "WEAR", "WYLE", "YARE", "YAWL", "YEAR", "ALE", "ARE", "AWE", "AWL", "AYE", "EAR", "ERA", "LAR", "LAW", "LAY", "LEA", "LEY", "LYE", "RAW", "RAY", "REA", "RYA", "RYE", "WAE", "WAR", "WAY", "WEY", "WRY", "WYE", "YAR", "YAW", "YEA", "YER", "YEW", "AE", "AL", "AR", "AW", "AY", "EL", "ER", "EW", "LA", "RE", "WE", "YA", "YE", "A" } },
        {"BASHER", new HashSet<string> { "BASHER","REHABS","BRASH","HERBS","REHAB","BARES","BASER","BEARS","BRAES","SABER","SABRE","HARES","HEARS","RHEAS","SHARE","SHEAR","BASH","BRAH","HERB","ARBS","BARE","BARS","BASE","BEAR","BRAE","BRAS","REBS","SABE","HAES","HARE","HEAR","HERS","RAHS","RASH","RESH","RHEA","SHEA","SHER","ARES","ARSE","EARS","ERAS","RASE","SEAR","SERA","BAH","ABS","ARB","BAE","BAR","BAS","BRA","REB","SAB","AHS","ASH","HAE","HAS","HER","HES","RAH","SHA","SHE","AES","ARE","ARS","EAR","ERA","ERS","RAS","REA","RES","SAE","SEA","SER","AB","BA","BE","AH","EH","HA","HE","SH","AE","AR","AS","ER","ES","RE"} },
        { "INASEL", new HashSet<string> { "ALIENS", "ALINES", "ELAINS", "LIANES", "SALINE", "SILANE", "AISLE", "ALIEN", "ALINE", "ANILE", "ANILS", "ANISE", "ELAIN", "ELANS", "LANES", "LEANS", "LENIS", "LIANE", "LIENS", "LINES", "NAILS", "SLAIN", "SNAIL", "AILS", "AINS", "ALES", "ANES", "ANIL", "ANIS", "EINA", "ELAN", "ILEA", "ISLE", "LAIN", "LANE", "LASE", "LEAN", "LEAS", "LEIS", "LENS", "LIAS", "LIEN", "LIES", "LINE", "LINS", "NAIL", "NAIS", "NILS", "SAIL", "SAIN", "SALE", "SANE", "SEAL", "SIAL", "SINE", "AES", "AIL", "AIN", "AIS", "ALE", "ALS", "ANE", "ANI", "ELS", "ENS", "INS", "LAS", "LEA", "LEI", "LIE", "LIN", "LIS", "NAE", "NAI", "NIL", "SAE", "SAI", "SAL", "SAN", "SEA", "SEI", "SEL", "SEN", "SIN", "A", "I", "AE", "AI", "AL", "AN", "AS", "EL", "EN", "ES", "IN", "IS", "LA", "LI", "NA", "NE", "SI" }},
         {   "UBCREH", new HashSet<string> { "BRUH", "CHERUB", "CUBER", "RUCHE", "BUHR", "CHUB", "CUBE", "CURB", "CURE", "ECRU", "ERHU", "HERB", "RUBE", "URBE", "BUR", "CRU", "CUB", "CUE", "CUR", "ECU", "HER", "HUB", "HUE", "REB", "REC", "RUB", "RUE", "URB", "BE", "BU", "EH", "ER", "HE", "RE", "UH" } },
        {  "WYDOSR", new HashSet<string> { "DROWSY", "DOWRY", "ROWDY", "SWORD", "WORDS", "WORDY", "DORS", "DORY", "DOWS", "DRYS", "RODS", "ROSY", "ROWS", "SORD", "WORD", "WORS", "YODS", "YOWS", "DOR", "DOS", "DOW", "DRY", "ODS", "ORS", "ROD", "ROW", "SOD", "SOW", "SOY", "SWY", "WOS", "WRY", "YOD", "YOW", "DO", "OD", "OR", "OS", "OW", "OY", "SO", "WO", "YO" } },
        { "BSAINR", new HashSet<string> { "NAI", "BIS", "BRIS", "BAN", "SIB", "BARS", "BRA", "AS", "ABRI", "A", "RAN", "RIB", "AIRNS", "BA", "BIN", "SI", "NAB", "ARBS", "AB", "BI", "RAINS", "BRINS", "RANIS", "BARN", "RIN", "BRAIN", "BRANS", "SAN", "NA", "BIAS", "AINS", "BARNS", "NABIS", "NIBS", "NIB", "I", "ANI", "ABS", "BAIS", "ARB", "INS", "RIBS", "BAIRN", "AI", "SABIR", "RABI", "IN", "IS", "BAR", "BANI", "BAIRNS", "NABS", "BRAINS", "SAB", "BAS", "AIN", "SARIN", "BANS", "BRIN", "AN", "SNIB", "NARIS", "ISBA", "BASIN", "BINS", "BRAS", "AR", "BRAN", "ABRIS", "SABIN" } },
        { "PACKER", new HashSet<string> { "A","PACKER","REPACK","CRAKE","CREAK","CAPER","CARPE","CRAPE","PACER","RECAP","PACK","PECK","CAKE","CARK","PARK","PEAK","PERK","RACK","RECK","CAPE","CARP","CRAP","PACE","RAKE","ACER","ACRE","APER","CARE","PARE","PEAR","RACE","RAPE","REAP","ACK","KEP","CAP","CEP","PAC","PEC","ARK","ERK","KAE","KEA","ACE","APE","ARC","CAR","PAR","PEA","PER","PRE","RAP","REC","REP","ARE","EAR","ERA","REA","KA","PA","PE","AE","AR","ER","RE" } }
    };
};

